// Generated RegisterSingleton code 
<<<<<<< HEAD
// Generated on 10/06/2025 Mon at 19:05:57.11 
=======
// Generated on Mon 10/06/2025 at 14:29:55.96 
>>>>>>> 7e49d2fb675296363a19f5e008e12362afe70909
 
container.RegisterSingleton<IView, AdaptiveColumnsPanelsContent>(nameof(AdaptiveColumnsPanelsContent)); 
container.RegisterSingleton<IView, AnimatedNavigationBarsContent>(nameof(AnimatedNavigationBarsContent)); 
container.RegisterSingleton<IView, AnimationsContent>(nameof(AnimationsContent)); 
container.RegisterSingleton<IView, AnimationToolsContent>(nameof(AnimationToolsContent)); 
container.RegisterSingleton<IView, BindingTemplateContent>(nameof(BindingTemplateContent)); 
container.RegisterSingleton<IView, BordersContent>(nameof(BordersContent)); 
container.RegisterSingleton<IView, ButtonsContent>(nameof(ButtonsContent)); 
container.RegisterSingleton<IView, CalendarsContent>(nameof(CalendarsContent)); 
container.RegisterSingleton<IView, CanvasContent>(nameof(CanvasContent)); 
container.RegisterSingleton<IView, ChartsContent>(nameof(ChartsContent)); 
container.RegisterSingleton<IView, CheckBoxsContent>(nameof(CheckBoxsContent)); 
container.RegisterSingleton<IView, ComboBoxsContent>(nameof(ComboBoxsContent)); 
container.RegisterSingleton<IView, CustomPanelsContent>(nameof(CustomPanelsContent)); 
container.RegisterSingleton<IView, DataContextTemplateContent>(nameof(DataContextTemplateContent)); 
container.RegisterSingleton<IView, DatasContent>(nameof(DatasContent)); 
container.RegisterSingleton<IView, DockPanelContent>(nameof(DockPanelContent)); 
container.RegisterSingleton<IView, DotnetContent>(nameof(DotnetContent)); 
container.RegisterSingleton<IView, DragandDropContent>(nameof(DragandDropContent)); 
container.RegisterSingleton<IView, GradientsContent>(nameof(GradientsContent)); 
container.RegisterSingleton<IView, GridsContent>(nameof(GridsContent)); 
container.RegisterSingleton<IView, GridSplittersContent>(nameof(GridSplittersContent)); 
container.RegisterSingleton<IView, HtmlPresentersContent>(nameof(HtmlPresentersContent)); 
container.RegisterSingleton<IView, InteropsContent>(nameof(InteropsContent)); 
container.RegisterSingleton<IView, ItemsControlsContent>(nameof(ItemsControlsContent)); 
container.RegisterSingleton<IView, JSLibsContent>(nameof(JSLibsContent)); 
container.RegisterSingleton<IView, LayoutTransformerContent>(nameof(LayoutTransformerContent)); 
container.RegisterSingleton<IView, ListBoxsContent>(nameof(ListBoxsContent)); 
container.RegisterSingleton<IView, MvvmTemplateContent>(nameof(MvvmTemplateContent)); 
container.RegisterSingleton<IView, MySliderContent>(nameof(MySliderContent)); 
container.RegisterSingleton<IView, PopupsContent>(nameof(PopupsContent)); 
container.RegisterSingleton<IView, ProgressBarsContent>(nameof(ProgressBarsContent)); 
container.RegisterSingleton<IView, ProjectItemContent>(nameof(ProjectItemContent)); 
container.RegisterSingleton<IView, ProjectTemplateContent>(nameof(ProjectTemplateContent)); 
container.RegisterSingleton<IView, RadioButtonsContent>(nameof(RadioButtonsContent)); 
container.RegisterSingleton<IView, RatingContent>(nameof(RatingContent)); 
container.RegisterSingleton<IView, RenderTransformsContent>(nameof(RenderTransformsContent)); 
container.RegisterSingleton<IView, ResourceTemplateContent>(nameof(ResourceTemplateContent)); 
container.RegisterSingleton<IView, ScrollViewerContent>(nameof(ScrollViewerContent)); 
container.RegisterSingleton<IView, SliderContent>(nameof(SliderContent)); 
container.RegisterSingleton<IView, SlidersContent>(nameof(SlidersContent)); 
container.RegisterSingleton<IView, StackPanelsContent>(nameof(StackPanelsContent)); 
container.RegisterSingleton<IView, StaggeredPanelsContent>(nameof(StaggeredPanelsContent)); 
container.RegisterSingleton<IView, StylesContent>(nameof(StylesContent)); 
container.RegisterSingleton<IView, TableControlsContent>(nameof(TableControlsContent)); 
container.RegisterSingleton<IView, TextBoxsContent>(nameof(TextBoxsContent)); 
container.RegisterSingleton<IView, ToastUIEditorContent>(nameof(ToastUIEditorContent)); 
container.RegisterSingleton<IView, ToggleButtonsContent>(nameof(ToggleButtonsContent)); 
container.RegisterSingleton<IView, TransContentContent>(nameof(TransContentContent)); 
container.RegisterSingleton<IView, TreeMapsContent>(nameof(TreeMapsContent)); 
container.RegisterSingleton<IView, UniformGridsContent>(nameof(UniformGridsContent)); 
container.RegisterSingleton<IView, ViewboxContent>(nameof(ViewboxContent)); 
container.RegisterSingleton<IView, WrapPanelsContent>(nameof(WrapPanelsContent)); 
container.RegisterSingleton<IView, XamlReaderContent>(nameof(XamlReaderContent)); 
